### ISSUE TITLE
How to file Images after Rendering ? i couldnt find them in Output or Outputs folder ! pls help

### ISSUE THREAD

**Issue by laichaoyi** [pokewizardSAM/Stable-Diffusion-portable#2]
I couldnt find any images in Output or Outputs after generating. Where is them ? Pls help ! it alway disconnect in realtime...i run on Colab Pro...runtime short disconected always !

**Comment by BlueNecko** [comment]
The images are saved inside outputs folder of your Google drive. About disconnection though can't help much, you have to keep the Colab window open and keep it active by clicking here and there in the logs every 10-15min or so

**Comment by BlueNecko** [comment]
If you want you can also set custom path for saving images in Stable diffusion settings

**Comment by laichaoyi** [comment]
i moved your path all to /content/drive/MyDrive/ all datas are no longer storage in. Colab Drive anymore. So that, i couldnt filnd any generated-images in Output or Outputs (why you made 2 folders like this ? i dont understand, pls help !)

**Comment by BlueNecko** [comment]
Ahem... So basically there is a default location in stable diffusion for saving images in output directory but moving the generated images from output directory to somewhere else or to Google drive will take a lot of time(why? Because the runtime of a Colab notebook is limited and your data gets deleted after you close your notebook so basically you loose your images too if not saved somewhere else )

So to prevent that I set it up to directly store the generated images in an outputs folder in your Google drive.

 If even after running the program you are not able to see the outputs folder in your drive then try creating one folder named "outputs" in you drive then it should work as expected.

**Comment by laichaoyi** [comment]
but i didnt see any images in outputs there. Because i want to upload/download many files into Google Drive for conveience :(( how to fix in google drive ?? pls help !

**Comment by BlueNecko** [comment]
which install type are you facing this problem with , have you tried fresh install method yet. if the prebuilt installation image is not working try to create a fresh install and if that works then back it up to your drive.

I dont understand where the bug is here , i would be helpfull if you could provide more context to it

**Comment by laichaoyi** [comment]
I would like a version works on Google Drive because Colab drive has 80 Gb,too small storage. So that, i edited your code and move all paths to Google Drive. My problem is how can find generated-images after rendering. Where is it ? how can you fix it to save on Google Drive instead of saving in Colab drive ? beucause i saw 2 folders : Output and Outputs but empty for both. Pls help me this !!!!

**Comment by laichaoyi** [comment]
and how can i storage and use models (checkpoint,lora,..) outside of Colab drive such as  : my google drive or other's google drive (shortcuts ) ???

**Comment by laichaoyi** [comment]
ive test models downloader from GUI but i couldnt find its location on Colab drive and google Drive. Where is it ?

**Comment by BlueNecko** [comment]
> edited your code and move all paths to Google Drive

if you used the load_basic_img then you didnt have to do that, It's already set to save the images in google drive by default. 

if you are using other methods or so then you can manually setup the desired path in stable diffusion webui to 
`/content/gdrive/MyDrive/outputs`  note that this is also the path where your images are saved by default in the basic_img

refrence: https://imgur.com/gallery/y60fspa


> and how can i storage and use models (checkpoint,lora,..) outside of Colab drive such as : my google drive or other's google drive (shortcuts ) ???

using files from your drive or others drive are pretty easy, either you can manully copy files from you remote location to your colab every time (assuming you have collab pro with lots of storage) , other wise you can share a folders edit permission  containing checkpoints and loras inside it with other gmail accounts and then setting up a manual path for checkpoints in the comand in the 3rd step>>  `--ckpt-dir "write the path to checkpoint folder "`  add this at the end launch.py 
so that it points to the remote directory for checkpoints. 

before doint this check once if the checkpoint folder is accessible to you in google drive, if not then save a shotcut in your drive first then try the above methods

**Comment by BlueNecko** [comment]
i will probably add the feature for using a remote directory once i get some free time , till then try these steps

**Comment by BlueNecko** [comment]
> ive test models downloader from GUI but i couldnt find its location on Colab drive and google Drive. Where is it ?

`Content/Sd-my-fork/models/`. Inside this folder

**Comment by laichaoyi** [comment]
> > ive test models downloader from GUI but i couldnt find its location on Colab drive and google Drive. Where is it ?
> 
> `Content/Sd-my-fork/models/`. Inside this folder

i found it saved to outside of Sd-my-fork . In the root of directory. How can modifiy default path for it ?

**Comment by BlueNecko** [comment]
> > > ive test models downloader from GUI but i couldnt find its location on Colab drive and google Drive. Where is it ?
> > 
> > 
> > `Content/Sd-my-fork/models/`. Inside this folder
> 
> i found it saved to outside of Sd-my-fork . In the root of directory. How can modifiy default path for it ?

It totally depends on how and where your are downloading, try to check the path before downloading.
By default if you are using model downloader , before pasting link for download chooses what kind of model it is so that I gets downloaded to right path. Otherwise instead of banging your head in the wall just copy the files to their respective folder inside models. Simple 


Btw I have exam today so can't help much rn ☠️ , wish me luck

**Comment by laichaoyi** [comment]
> > > > ive test models downloader from GUI but i couldnt find its location on Colab drive and google Drive. Where is it ?
> > > 
> > > 
> > > `Content/Sd-my-fork/models/`. Inside this folder
> > 
> > 
> > i found it saved to outside of Sd-my-fork . In the root of directory. How can modifiy default path for it ?
> 
> It totally depends on how and where your are downloading, try to check the path before downloading. By default if you are using model downloader , before pasting link for download chooses what kind of model it is so that I gets downloaded to right path. Otherwise instead of banging your head in the wall just copy the files to their respective folder inside models. Simple
> 
> Btw I have exam today so can't help much rn ☠️ , wish me luck

i think its a bug, because i carefully choose checkpoints type and paste the link for checkpoint model but it saved in the root of directory automatically !

**Comment by BlueNecko** [comment]
Sure, I will look into it. Send the links for the checkpoints and the extension you used to download

**Comment by laichaoyi** [comment]
> 

i fixed it by moving model files to gDrive and tried to change dir to gg Drive already. My runtime is too short to keep files in Colab drive. Therefore i moved it out !
